import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireSuperAdmin } from "@/lib/authorization";
import { z } from "zod";
const schema=z.object({id:z.string().uuid().nullable().optional(),name:z.string().trim().min(2).max(80),permissionIds:z.array(z.string().uuid()).max(100)});
export async function GET(){const admin=await requireSuperAdmin();if(!admin)return NextResponse.json({error:"Accès refusé."},{status:403});const roles=await prisma.role.findMany({orderBy:{name:"asc"},select:{id:true,name:true,permissions:{select:{permission:{select:{id:true,key:true,description:true}}}},_count:{select:{users:true}}}});return NextResponse.json({roles:roles.map(r=>({...r,permissions:r.permissions.map(x=>x.permission)}))})}
export async function POST(req:Request){return save(req,false)}
export async function PUT(req:Request){return save(req,true)}
async function save(req:Request,editing:boolean){const admin=await requireSuperAdmin();if(!admin)return NextResponse.json({error:"Accès refusé."},{status:403});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Données invalides."},{status:400});const {id,name,permissionIds}=parsed.data;if(editing&&!id)return NextResponse.json({error:"Rôle introuvable."},{status:400});if(name==="SUPER_ADMIN")return NextResponse.json({error:"Le rôle SUPER_ADMIN est protégé."},{status:400});const duplicate=await prisma.role.findFirst({where:{name,...(id?{NOT:{id}}:{})}});if(duplicate)return NextResponse.json({error:"Ce nom de rôle existe déjà."},{status:409});const valid=await prisma.permission.findMany({where:{id:{in:permissionIds}},select:{id:true}});if(valid.length!==permissionIds.length)return NextResponse.json({error:"Une ou plusieurs permissions sont invalides."},{status:400});const role=editing?await prisma.role.update({where:{id:id!},data:{name,permissions:{deleteMany:{},create:valid.map(p=>({permissionId:p.id}))}}}):await prisma.role.create({data:{name,permissions:{create:valid.map(p=>({permissionId:p.id}))}}});await prisma.auditLog.create({data:{actorId:admin.id,action:editing?"ROLE_UPDATED":"ROLE_CREATED",entity:"Role",entityId:role.id,metadata:{name,permissionCount:valid.length}}});return NextResponse.json({ok:true,roleId:role.id})}
export async function DELETE(req:Request){const admin=await requireSuperAdmin();if(!admin)return NextResponse.json({error:"Accès refusé."},{status:403});const body=await req.json();if(typeof body.id!=="string")return NextResponse.json({error:"Rôle introuvable."},{status:400});const role=await prisma.role.findUnique({where:{id:body.id},select:{id:true,name:true,_count:{select:{users:true}}}});if(!role)return NextResponse.json({error:"Rôle introuvable."},{status:404});if(role.name==="SUPER_ADMIN")return NextResponse.json({error:"Le rôle SUPER_ADMIN est protégé."},{status:400});if(role._count.users>0)return NextResponse.json({error:"Ce rôle est encore attribué à des utilisateurs."},{status:409});await prisma.role.delete({where:{id:role.id}});await prisma.auditLog.create({data:{actorId:admin.id,action:"ROLE_DELETED",entity:"Role",entityId:role.id,metadata:{name:role.name}}});return NextResponse.json({ok:true})}