"use client";
import { useState } from "react";
type U = {id:string;firstName:string;lastName:string;email:string;type:string;studentStatus:string|null;isActive:boolean;school:{name:string}|null;academicLevel:{name:string}|null;program:{name:string}|null;role:{id:string;name:string}|null};
type R = {id:string;name:string};
type Q = {id:string;requestedAt:string;user:{firstName:string;lastName:string;email:string}};
export default function AllUsersManager({initialUsers,roles,initialRequests}:{initialUsers:U[];roles:R[];initialRequests:Q[]}){
 const [users,setUsers]=useState(initialUsers); const [requests,setRequests]=useState(initialRequests); const [query,setQuery]=useState(""); const [message,setMessage]=useState("");
 async function setRole(id:string,type:"USER"|"ADMIN"){const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,type})});const data=await response.json();if(!response.ok){setMessage(data.error||"Échec");return;}setUsers(a=>a.map(u=>u.id===id?{...u,type}:u));setMessage("Rôle modifié.");}
 async function decide(id:string,action:"APPROVE"|"REJECT"){const response=await fetch("/api/admin/password-reset-requests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});const data=await response.json();if(!response.ok){setMessage(data.error||"Échec");return;}setRequests(a=>a.filter(q=>q.id!==id));setMessage(data.message||"Demande traitée.");}
 const visible=users.filter(u=>(u.firstName+" "+u.lastName+" "+u.email).toLowerCase().includes(query.toLowerCase()));
 return <div className="space-y-8">{message&&<p className="rounded-xl bg-sky-50 p-3">{message}</p>}
 <section className="card p-5"><h2 className="text-xl font-bold">Demandes de mot de passe ({requests.length})</h2>{requests.map(q=><div key={q.id} className="flex items-center justify-between gap-3 border-t py-3"><div>{q.user.firstName} {q.user.lastName}<p className="text-sm text-slate-500">{q.user.email}</p></div><div className="flex gap-2"><button onClick={()=>decide(q.id,"APPROVE")} className="rounded bg-emerald-600 px-3 py-2 text-white">Valider</button><button onClick={()=>decide(q.id,"REJECT")} className="rounded border px-3 py-2">Refuser</button></div></div>)}</section>
 <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-bold">Tous les comptes ({users.length})</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un nom ou un e-mail" className="mt-3 w-full rounded-xl border p-3"/></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-3">Compte</th><th className="p-3">Niveau académique</th><th className="p-3">Rôle</th><th className="p-3">Action</th></tr></thead><tbody>{visible.map(u=><tr key={u.id} className="border-t"><td className="p-3">{u.firstName} {u.lastName}<p className="text-slate-500">{u.email}</p></td><td className="p-3">{u.academicLevel?.name||"—"}<p>{u.program?.name||""}</p></td><td className="p-3">{u.type}</td><td className="p-3">{u.type==="SUPER_ADMIN"?"Protégé":u.type==="USER"?<button onClick={()=>setRole(u.id,"ADMIN")} className="rounded bg-sky-600 px-3 py-2 text-white">Attribuer admin</button>:<button onClick={()=>setRole(u.id,"USER")} className="rounded border px-3 py-2">Retirer admin</button>}</td></tr>)}</tbody></table></div></section></div>;
}