"use client";
import { useState } from "react";
type Permission={id:string;key:string;description:string|null};
type Role={id:string;name:string;permissions:Permission[];_count:{users:number}};
export default function RolesManager({initialRoles,permissions}:{initialRoles:Role[];permissions:Permission[]}) {
 const [roles,setRoles]=useState(initialRoles),[name,setName]=useState(""),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const reset=()=>{setEditing(null);setName("");setSelected([]);setMessage("")};
 const edit=(r:Role)=>{setEditing(r.id);setName(r.name);setSelected(r.permissions.map(p=>p.id));setMessage("")};
 const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/roles",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing,name,permissionIds:selected})});const d=await r.json();if(!r.ok)throw Error(d.error);const fresh=await fetch("/api/admin/roles");setRoles((await fresh.json()).roles);reset();setMessage("Rôle enregistré.")}catch(e){setMessage(e instanceof Error?e.message:"Une erreur est survenue.")}finally{setBusy(false)}}
 async function remove(r:Role){if(!confirm(`Supprimer le rôle « ${r.name} » ?`))return;setBusy(true);try{const res=await fetch("/api/admin/roles",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id})});const d=await res.json();if(!res.ok)throw Error(d.error);setRoles(x=>x.filter(i=>i.id!==r.id));setMessage("Rôle supprimé.")}catch(e){setMessage(e instanceof Error?e.message:"Une erreur est survenue.")}finally{setBusy(false)}}
 return <div className="grid gap-6 lg:grid-cols-[1fr_420px]"><section className="space-y-4">{roles.map(r=><article key={r.id} className="card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-black">{r.name}</h2>{r.name==="SUPER_ADMIN"&&<span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Protégé</span>}</div><p className="mt-1 text-sm text-slate-500">{r._count.users} utilisateur(s) · {r.permissions.length} permission(s)</p></div>{r.name!=="SUPER_ADMIN"&&<div className="flex gap-2"><button onClick={()=>edit(r)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Modifier</button><button onClick={()=>remove(r)} disabled={busy} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-semibold text-red-600">Supprimer</button></div>}</div><div className="mt-4 flex flex-wrap gap-2">{r.permissions.map(p=><span key={p.id} className="rounded-full bg-sky-50 px-3 py-1.5 text-xs font-semibold text-sky-700">{p.key}</span>)}</div></article>)}</section><section className="card h-fit p-6 lg:sticky lg:top-6"><h2 className="text-lg font-black">{editing?"Modifier le rôle":"Créer un rôle"}</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Éditeur de contenu" className="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-sky-400"/><div className="mt-5 max-h-[430px] space-y-2 overflow-y-auto">{permissions.map(p=><label key={p.id} className="flex cursor-pointer gap-3 rounded-xl border border-slate-100 p-3"><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)} className="mt-1 h-4 w-4 accent-sky-600"/><span><span className="block text-sm font-semibold">{p.key}</span><span className="text-xs text-slate-500">{p.description}</span></span></label>)}</div>{message&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{message}</p>}<div className="mt-5 flex gap-2"><button onClick={save} disabled={busy||!name.trim()} className="flex-1 rounded-xl bg-sky-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy?"Enregistrement...":editing?"Enregistrer":"Créer le rôle"}</button>{editing&&<button onClick={reset} className="rounded-xl border px-4 py-3 font-semibold">Annuler</button>}</div></section></div>;
}