"use client";
import Link from "next/link";
import { useState } from "react";
type O={id:string;name:string;kind?:string|null};
export default function BulkImportForm({levels,subjects,schools,programs}:{levels:O[];subjects:O[];schools:O[];programs:O[]}){
 const [files,setFiles]=useState<File[]>([]),[targetType,setTargetType]=useState<"ELEVE"|"ETUDIANT">("ELEVE"),[academicLevelId,setAcademicLevelId]=useState(""),[category,setCategory]=useState("EXERCICE"),[subjectId,setSubjectId]=useState(""),[schoolId,setSchoolId]=useState(""),[programId,setProgramId]=useState(""),[titlePrefix,setTitlePrefix]=useState(""),[year,setYear]=useState(""),[status,setStatus]=useState("DRAFT"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const options=levels.filter(l=>targetType==="ELEVE"?(l.kind!=="UNIVERSITAIRE"&&!["Licence 1","Licence 2","Licence 3"].includes(l.name)):(l.kind==="UNIVERSITAIRE"||["Licence 1","Licence 2","Licence 3"].includes(l.name)));
 function changeType(value:"ELEVE"|"ETUDIANT"){setTargetType(value);setAcademicLevelId("");setProgramId("");setCategory("EXERCICE");}
 async function submit(){setMessage("");if(!files.length){setMessage("Sélectionne au moins un PDF.");return;}if(!academicLevelId){setMessage("Sélectionne le niveau, la classe ou la série.");return;}if(targetType==="ETUDIANT"&&!programId){setMessage("Sélectionne la filière.");return;}const data=new FormData();files.forEach(file=>data.append("files",file));data.set("targetType",targetType);data.set("academicLevelId",academicLevelId);data.set("category",category);data.set("titlePrefix",titlePrefix);data.set("subjectId",subjectId);data.set("schoolId",schoolId);data.set("programId",programId);data.set("year",year);data.set("status",status);setBusy(true);try{const response=await fetch("/api/admin/exams/bulk-import",{method:"POST",body:data});const result=await response.json();if(!response.ok)throw Error(result.error||"Import impossible.");setMessage(result.count+" épreuve(s) importée(s) avec succès.");setFiles([]);}catch(e){setMessage(e instanceof Error?e.message:"Erreur réseau.");}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-4xl"><Link href="/admin/exams" className="text-sm font-semibold text-sky-700">← Retour aux épreuves</Link><section className="card mt-4 p-6"><p className="text-sm font-bold text-sky-600">Études Space · Administration</p><h1 className="mt-2 text-3xl font-black">Importer plusieurs épreuves</h1><p className="mt-2 text-slate-500">Sélectionne plusieurs PDF et attribue les informations communes. Le titre de chaque épreuve sera basé sur le nom du fichier, avec le préfixe facultatif ci-dessous.</p>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Fichiers PDF (20 maximum)<input className="mt-2 block w-full rounded-xl border bg-white p-3" type="file" accept="application/pdf,.pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><span className="mt-1 block text-xs text-slate-500">{files.length} fichier(s) sélectionné(s), 50 Mo maximum par fichier.</span></label>
 <label className="text-sm font-semibold">Préfixe du titre (facultatif)<input value={titlePrefix} onChange={e=>setTitlePrefix(e.target.value)} placeholder="Ex. Mathématiques - Session 2025" className="mt-2 w-full rounded-xl border p-3"/></label>
 <label className="text-sm font-semibold">Public<select value={targetType} onChange={e=>changeType(e.target.value as "ELEVE"|"ETUDIANT")} className="mt-2 w-full rounded-xl border p-3"><option value="ELEVE">Élève</option><option value="ETUDIANT">Étudiant</option></select></label>
 <label className="text-sm font-semibold">Niveau / classe / série<select value={academicLevelId} onChange={e=>setAcademicLevelId(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Sélectionner</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 <label className="text-sm font-semibold">Catégorie<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full rounded-xl border p-3">{(targetType==="ELEVE"?[["EXERCICE","Exercices"],["ANCIEN_SUJET","Anciens sujets"],["EXAMEN_BLANC","Examens blancs"],["AUTRE","Autre"]]:[["EXERCICE","Exercices"],["CONTROLE_CONTINU","Contrôle continu (CC)"],["SESSION_NORMALE","Session normale"],["SIMULATION_BTS_DUT","Simulation BTS / DUT"]]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label className="text-sm font-semibold">Matière<select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Non précisée</option>{subjects.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 {targetType==="ETUDIANT"&&<label className="text-sm font-semibold">Filière<select value={programId} onChange={e=>setProgramId(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Sélectionner</option>{programs.filter(p=>p.kind==="FILIERE").map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
 <label className="text-sm font-semibold">Établissement<select value={schoolId} onChange={e=>setSchoolId(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Non précisé</option>{schools.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 <label className="text-sm font-semibold">Année<input type="number" min="1900" max="2100" value={year} onChange={e=>setYear(e.target.value)} placeholder="2025" className="mt-2 w-full rounded-xl border p-3"/></label>
 <label className="text-sm font-semibold">Statut<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="DRAFT">Brouillon</option><option value="PUBLISHED">Publier immédiatement</option><option value="ARCHIVED">Archivé</option></select></label></div>
 {files.length>0&&<div className="mt-4 max-h-44 overflow-auto rounded-xl border bg-white p-3 text-sm">{files.map((f,i)=><p key={f.name+i} className="py-1">{i+1}. {f.name} · {(f.size/1024/1024).toFixed(1)} Mo</p>)}</div>}
 {message&&<p role="status" className="mt-4 rounded-xl bg-sky-50 p-3 text-sm text-sky-800">{message}</p>}
 <button onClick={submit} disabled={busy||!files.length} className="mt-6 rounded-xl bg-sky-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?"Importation en cours…":"Importer "+files.length+" épreuve(s)"}</button></section></div></main>;
}
